PRIVET FRIENDS ETO MOY CODE
NiksBrn/Giga-Algebra pull request #4
Opened 2024-10-31 19:27 UTC by PetrYakushev

2024-10-31 19:59 UTC, t33nsy requested changes

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +        int num1 = Big_int.get_last()->value; //������ ����� ������� �����
бесполезные строки, надо исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +        int i = 1;
прямо вот до сюда все бесполезно

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +        while (i < k1) { //���� ��� ��������� ���� �������� ����� �����
переменная `i` и итерация по `i` - бесполезно

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +    }
снова итерация по неиспользующемуся `i`, нужно исправлять на нормальную итерацию по node->next

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +        }
это не сработает, если разряд увеличивается, к примеру число 9999, ты дойдешь до первой девятки и просто уйдешь в nullptr и сегфолт

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +        }
эти приколы непонятны, после прокрутки в голове вроде они не сработают
исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +}
функция должна возвращать NaturalNumber&, возврата нет - ошибка и аварийное завершение
исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +    }
подумать насчет остальных цифр
спросить архитектора
исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +    if (Big_int.get_first()->value * c >= 10) { // ���� ��������� ��������� ����� ��� ���������� �����
возможна ошибка? (-66<char<65, 9*9=81)

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +    if (Big_int.get_first()->value * c >= 10) { // ���� ��������� ��������� ����� ��� ���������� �����
@NiksBrn проверишь потом, приводит ли автоматически к инту умножение char на int, пока под вопросом

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +        int desatok = (Big_int.get_first()->value * c) / 10; // ������� �� ���������
транслитерация

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +    }
очень сложно
упростить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +}
функция должна возвращать `NaturalNumber &`, не возвращает ничего
как итог - аварийное завершение
исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +}
функция должна возвращать NaturalNumber &, не возвращает ничего
как итог - аварийное завершение
исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +}
функция должна возвращать NaturalNumber &, не возвращает ничего
как итог - аварийное завершение
исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +    }
скорее всего неверно, нужно посмотреть и исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +
нет проверок на простейшее - размеры
если размер первого числа меньше второго, в натуральных числах вычитание не выполняется)
исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +    }
`point` нигде не учитывается (10 для дополнения берутся из воздуха, не из следующего разряда)
снова итерация по `i`
непонятное ветвление, пересмотреть
исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +    }
`point` только для последнего разряда?)

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +        if (k.Big_int.get_first()->value != 1) {
нельзя обращаться к `k.Big_Int`
`Big_Int` - `private` поле
есть геттер
исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +        if (k.Big_int.get_first()->value != 1) {
да и в принципе зачем это условие?
если смотреть на него, то получается, что при запросе умножить число на 10 (10^1) мы получим то же число? почему?
исправить

2024-10-31 19:59 UTC, t33nsy commented on sources/tmp_modules/first_module_NN.cpp
> +    if ((Big_int.get_size() != 1) && (Big_int.get_first()->value != 0)) {
необязательные условия, пересмотреть
нагромождение кода

2024-10-31 19:59 UTC, t33nsy commented on tests/NaturalNumberTest.cpp
> +#include "NaturalNumber.h"
на все тесты сразу -- нельзя делать тестирование нескольких ситуаций в одном тесте
разделить

2024-10-31 19:59 UTC, t33nsy commented on tests/NaturalNumberTest.cpp
> +    EXPECT_TRUE(n1.NZER_N_B(), false);
?
`EXPECT_TRUE` принимает один аргумент
и делает то, что написано у него в названии

2024-10-31 19:59 UTC, t33nsy commented on tests/NaturalNumberTest.cpp
> +}
функция возвращает `enum`, значит и сравнения в тестировании делать со значениями этого `enum`

2024-10-31 19:59 UTC, t33nsy commented on tests/NaturalNumberTest.cpp
> +    n.add(999);
че за `add()`

2024-10-31 19:59 UTC, t33nsy commented on tests/NaturalNumberTest.cpp
> +    EXPECT_EQ(n.get_value(), 10000);
если бы `999+1==10000`, было бы славно

2024-10-31 19:59 UTC, t33nsy commented on tests/NaturalNumberTest.cpp
> +    EXPECT_EQ(n.get_value(), 10000);
что за get_value? 
здесь и дальше
исправить

2024-10-31 19:59 UTC, t33nsy commented on tests/NaturalNumberTest.cpp
> +    EXPECT_EQ(result.get_value(), 579);
.

2024-10-31 19:59 UTC, t33nsy commented on tests/NaturalNumberTest.cpp
> +    EXPECT_TRUE(n1.MUL_Nk_N(k), 3200);
32*10^100!=3200

2024-10-31 20:04 UTC, t33nsy commented
на самом деле не сильно плохо, но исправить нужно быстро, чтобы остальные могли делать

2024-11-01 13:41 UTC, Greyrest commented on sources/tmp_modules/first_module_NN.cpp
Посмотри внимательно до какого именно значения ты итерируешься

2024-11-01 13:43 UTC, Greyrest commented on sources/tmp_modules/first_module_NN.cpp
> +            for (int i = 0; i < k.Big_int.get_size(); i++) {
Подумай внимательно до какого значения ты итерируешься в цикле. Также применение метода get_size() неверно

2024-11-01 23:28 UTC, PetrYakushev commented on sources/tmp_modules/first_module_NN.cpp
> +
В условиях написано: "Вычитание из первого **большего** натурального числа второго **меньшего** или **равного**", так что проверка на размеры не требуется

2024-11-01 23:28 UTC, PetrYakushev commented on sources/tmp_modules/first_module_NN.cpp
> +
@t33nsy

2024-11-06 21:22 UTC, merged